WEBSOCKET ws://localhost:5000/notifications-hub
Content-Type: application/json

// RS (record separator) character at the end of the message is needed
===
{"protocol":"json","version":1}
===
{
    "arguments": ["This is the notification message."],
    "target": "SendNotification",
    "type": 1
}
===