name: Workshopper - Sessions API [Development]

on:
  push:
    branches: [ "develop" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    environment: development.container

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Workshopper.Api.Sessions/Dockerfile
          push: false