name: Workshopper - Tests

on:
  push:
    branches: [ "develop" ]

jobs:

  test:

    runs-on: ubuntu-latest
    environment: development

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Install dependencies
        run: dotnet restore
    
      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test