name: Workshopper - Deploy [Staging]

on:
  push:
    branches: [ "staging" ]
  workflow_run:
    workflows: [
        "Workshopper - API [Staging]",
        "Workshopper - Database Updater [Staging]",
        "Workshopper - Auth API [Staging]",
        "Workshopper - Sessions API [Staging]"
        ]
    types:
      - completed
    branches:
      - staging

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:

      - name: SSH into Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_PORT }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          passphrase: ${{ secrets.VM_PASSPRASE }}
          script_stop: true
          script: |
            cd /root
            docker compose stop
            docker system prune -a -f
            docker compose up -d