name: Workshopper - Deploy [Development]

on:
  workflow_run:
    workflows: [
        "Workshopper - API [Development]",
        "Workshopper - Database Updater [Development]",
        "Workshopper - Auth API [Development]",
        "Workshopper - Sessions API [Development]"
        ]
    types:
      - completed
    branches:
      - develop

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_PORT }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script_stop: true
          script: |
            cd /root
            docker compose stop
            docker system prune -a -f
            docker compose up -d