name: Workshopper - API [Staging]

on:
  push:
    branches: [ "staging" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    environment: staging

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/appsettings.staging.json'
        env:
          Database.ConnectionString: ${{ secrets.DATABASE_CONNECTION_STRING }}
          JwtSettings.SigningKey: ${{ secrets.JWT_SIGNING_KEY }}
          JwtSettings.Issuer: ${{ secrets.JWT_ISSUER }}
          JwtSettings.Audience: ${{ secrets.JWT_AUDIENCE }}
          JwtSettings.TokenExpiration: ${{ secrets.JWT_TOKEN_EXPIRATION }}
          FeatureFlagsSettings.Key: ${{ secrets.FEATURE_FLAGS_TOKEN }}
          FeatureFlagsSettings.PollingInterval: ${{ secrets.FEATURE_FLAGS_POLLING_INTERVAL }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Workshopper.Api/Dockerfile
          push: true
          tags: wmanka/workshopper-api:staging