name: Workshopper - Deploy [Development]

on:
  push:
    branches: [ "develop" ]
  workflow_run:
    workflows: [
        "Workshopper - API [Development]",
        "Workshopper - Database Updater [Development]",
        "Workshopper - Auth API [Development]",
        "Workshopper - Sessions API [Development]"
        ]
    types:
      - completed
    branches:
      - develop

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:

      - name: SSH into Development Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: ${{ secrets.VM_PORT }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script_stop: true
          script: |
            cd /root
            docker compose stop
            docker system prune -a -f
            docker compose up -d