name: Workshopper - Auth API [Development]

on:
  push:
    branches: [ "develop" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    environment: development

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/appsettings.json'
        env:
          Database.ConnectionString: ${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Workshopper.Api.Auth/Dockerfile
          push: true
          tags: wmanka/workshopper-api-auth:development